Repository necesito-un-trastero/id-doc-validator, pull requests merged in 2023-11, with the labels that each got.

#24 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#25 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#26 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#29 Review bruno
  CHANGELOG.md
  README.md
  package-lock.json
  src/__tests__/country_validations/de.test.js
  src/__tests__/country_validations/pt.test.js
  src/__tests__/index.test.js
  src/country_validations/pt.js
  src/index.js
  src/utils.js
Labels: enhancement

#23 Add PT validators
  package-lock.json
  src/__tests__/country_validations/pt.test.js
  src/country_validations/pt.js
Labels: enhancement, good first issue

#37 Create npm-publish.yml
  .github/workflows/npm-publish.yml
Labels: enhancement

#43 GB VAT and passport
  CHANGELOG.md
  README.md
  package.json
  src/__tests__/country_validations/gb.test.js
  src/__tests__/index.test.js
  src/__tests__/type_validations/passport.test.js
  src/country_validations/gb.js
  src/index.js
  src/type_validations/passport.js
Labels: enhancement
